### ISSUE TITLE
Can't export .maps please HELP

### ISSUE THREAD

**Issue by BandryPT** [JasonM97/Rust-Map-Editor#2]
When trying to export .maps i get this.

IndexOutOfRangeException: Index was outside the bounds of the array.
(wrapper managed-to-managed) System.Object.ElementAddr_4(object,int,int,int)
MapIO.saveTopologyLayer () (at Assets/Scripts/MapIO.cs:33)
MapIO.Save (System.String path) (at Assets/Scripts/MapIO.cs:208)
MapIOEditor.OnInspectorGUI () (at Assets/Editor/MapIOEditor.cs:36)
UnityEditor.InspectorWindow.DrawEditor (UnityEditor.Editor[] editors, System.Int32 editorIndex, System.Boolean rebuildOptimizedGUIBlock, System.Boolean& showImportedObjectBarNext, UnityEngine.Rect& importedObjectBarRect) (at C:/buildslave/unity/build/Editor/Mono/Inspector/InspectorWindow.cs:1374)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by Dezinater** [comment]
Should be fixed with the latest updates. Can you confirm it works for you and I'll close the issue?
