### ISSUE TITLE
Namespace "Protobuf" and "LZ4" could not be found

### ISSUE THREAD

**Issue by JameBestNA** [JasonM97/Rust-Map-Editor#3]
[Screenshot](https://gyazo.com/8b7f31f6e387fa36aaf372705e321c17)

How can i fix this issue?

**Comment by JustNir** [comment]
you need to add the missing references to both dll that are showen there in the WorldSerializaion script (theyre in Rust-Map-Editor-master\Assets\Plugins) and you need to chancge unity's .NET version to 4.x https://docs.unity3d.com/2018.2/Documentation/Manual/ScriptingRuntimeUpgrade.html
I did this and everything is working fine

**Comment by Dezinater** [comment]
The solution Just I posted should work. Can you confirm you're not having those errors anymore?
