### ISSUE TITLE
MapIO doesn't work

### ISSUE THREAD

**Issue by ultron6000** [JasonM97/Rust-Map-Editor#6]
So I've installed unity 2018.2.0 because the beta version was not available but the MapIO won't work it has an error and some other files too.
![Schermopname (67)](https://user-images.githubusercontent.com/120034361/206213703-1a141e58-67ec-43de-96b5-1e0d7e968593.png)
And I have no idea what to do.

**Comment by Dezinater** [comment]
Sorry I don't update this project anymore so it may not work with newer map files
Check out this project for an updated version https://github.com/Adsito/RustMapEditor
